// Itinerarios en inglés (británico). Las horas viven en itinerarios.ts.
import type { ItinId, TextoItin, EtiquetasItin } from './datosItinerarios'

export const ET_EN: EtiquetasItin = {
  titulo: 'The day, hour by hour', sub: 'This is what a day with us looks like in each place. They are real examples: we adjust the order to your pace, the light and the crowds.',
  volver: 'Back', ver: 'See the day hour by hour', dia: 'The day', comer: 'Food', ojo: 'Good to know', pedir: 'I want this day',
  precio: 'Price', viajeGuia: '+ the guide\'s ticket there, included in the fixed quote', porGrupo: 'per group', siguiente: 'Next',
  nota: 'You pay for entry tickets, trains and meals on the day; I tell you when and where.',
}

export const ITIN_EN: Record<ItinId, TextoItin> = {
  kioto: {
    titulo: 'Kyoto in a day', llegar: '≈ 45 min by train from Osaka',
    resumen: 'The torii of Fushimi Inari before the crowds arrive, the wooden temple of Kiyomizu, the streets of Gion and the Golden Pavilion in the late afternoon.',
    pasos: [
      { lugar: 'Your hotel in Osaka', que: 'I meet you in the lobby and we take the train together. I\'ll show you how to use an IC card for the whole day.' },
      { lugar: 'Fushimi Inari Taisha', que: 'We climb through the tunnels of red torii to the Yotsutsuji viewpoint, where most people turn back. Photos without the crowds.' },
      { lugar: 'Kiyomizu-dera', que: 'The wooden stage over the hillside, built without a single nail. We walk down the stone slopes of Sannenzaka and Ninenzaka.' },
      { lugar: 'Lunch in Higashiyama', que: 'Tofu, soba or a noodle set in a wooden house. If you need halal or vegetarian food, I choose the place with that in mind.' },
      { lugar: 'Gion and Hanamikoji', que: 'The teahouse district, Yasaka Shrine and the Shirakawa canal, the most photographed corner of Kyoto.' },
      { lugar: 'Kinkaku-ji, the Golden Pavilion', que: 'Taxi or bus up to the north. In the afternoon light the gold is reflected in the pond. It closes at 17:00.' },
      { lugar: 'Back to Osaka', que: 'I put you on the right train, or we travel back together to your hotel.' },
    ],
    comer: 'Kyoto is about tofu, vegetables and noodles. There are halal-certified ramen and restaurants near Gion.',
    ojo: 'There is a lot of walking and plenty of steps: wear comfortable shoes. In autumn (November) and cherry blossom season (April) we start even earlier.',
  },
  osaka: {
    titulo: 'Osaka on foot, eating', llegar: 'Starts at your hotel',
    resumen: 'The city of food. The castle in the morning, the market at lunchtime and the neon of Dōtonbori as night falls.',
    pasos: [
      { lugar: 'Your hotel', que: 'I pick you up and we go by metro. Osaka makes more sense on foot and hungry.' },
      { lugar: 'Osaka Castle', que: 'The moats and giant stone walls, the park and, if you like, the museum inside the keep with views from the top.' },
      { lugar: 'Kuromon Market', que: '"Osaka\'s kitchen": seafood skewers, Japanese fruit, sweet omelette. You eat standing up, stall by stall.' },
      { lugar: 'Shinsekai', que: 'The retro-feeling district under Tsūtenkaku Tower. Kushikatsu and old-fashioned games.' },
      { lugar: 'Hōzen-ji', que: 'A temple hidden in a stone alley between restaurants, with a statue covered in moss.' },
      { lugar: 'Dōtonbori', que: 'The canal and the giant illuminated signs. Freshly made takoyaki and a walk along the river as the lights come on.' },
      { lugar: 'End of the day', que: 'I drop you at your hotel or at the restaurant you have chosen for dinner.' },
    ],
    comer: 'Takoyaki, okonomiyaki and seafood. For halal, there are certified restaurants in Namba; I\'ll tell you which.',
    ojo: 'The day you eat the most: come hungry. On Sundays and public holidays Dōtonbori is packed; weekdays are better.',
  },
  nara: {
    titulo: 'Nara and its deer', llegar: '≈ 40 min by train from Osaka',
    resumen: 'Japan\'s first capital: deer roaming the park, the great bronze Buddha and a thousand stone lanterns in the forest.',
    pasos: [
      { lugar: 'Your hotel in Osaka', que: 'I pick you up and we take the Kintetsu train, which stops five minutes from the park.' },
      { lugar: 'Kōfuku-ji', que: 'The five-storey pagoda and the entrance to the park. This is where the deer start to appear.' },
      { lugar: 'Nara Park', que: 'More than a thousand free-roaming deer that bow if you give them deer crackers. I\'ll show you how, so they don\'t chase you.' },
      { lugar: 'Tōdai-ji', que: 'The 15-metre Great Buddha inside one of the largest wooden buildings in the world. And the pillar with the hole to squeeze through.' },
      { lugar: 'Lunch in Naramachi', que: 'The old merchants\' quarter. Noodles, kakinoha-zushi (sushi wrapped in persimmon leaf) or whatever you fancy.' },
      { lugar: 'Kasuga Taisha', que: 'The path of moss-covered stone lanterns among cedars, and the bronze lanterns hanging in the shrine.' },
      { lugar: 'Isui-en Garden and back', que: 'A Japanese garden with Mount Wakakusa behind it (closed on Tuesdays). Then the train back.' },
    ],
    comer: 'Nara is easy for food: noodles, persimmon-leaf sushi and tea sweets. Vegetarian options are no problem.',
    ojo: 'The deer nibble clothes if you hide crackers: give them all out or show your empty hands. Great with children.',
  },
  himeji: {
    titulo: 'Himeji, the white castle', llegar: '≈ 1 h by rapid train from Osaka',
    resumen: 'Japan\'s best-preserved original castle, inside, floor by floor. Then its garden and a temple at the top of Mount Shosha.',
    pasos: [
      { lugar: 'Your hotel in Osaka', que: 'I pick you up and we take the rapid train or the shinkansen, depending on the group\'s budget.' },
      { lugar: 'Himeji Castle', que: 'The "White Heron": we climb the six floors of original wood from 1609. I\'ll tell you how it was defended and where the archers hid.' },
      { lugar: 'Kōko-en Garden', que: 'Nine gardens at the foot of the castle, with carp ponds and a teahouse.' },
      { lugar: 'Lunch in Himeji', que: 'Anago (conger eel) or the local oden with ginger sauce. There are places with pork-free options.' },
      { lugar: 'Engyō-ji, Mount Shosha', que: 'Ropeway and forest up to a thousand-year-old wooden monastery on the mountain, where "The Last Samurai" was filmed.' },
      { lugar: 'Back to Osaka', que: 'Or a stop in Kobe to see the harbour lit up, if you still have the energy.' },
      { lugar: 'Arrival at the hotel', que: 'I leave you in the lobby.' },
    ],
    comer: 'Himeji is about conger eel and oden. I\'ll tell you which dishes contain pork or pork stock.',
    ojo: 'Inside the castle you go shoeless and the stairs are very steep: wear socks and avoid long skirts. It opens at 9:00.',
  },
  kobe: {
    titulo: 'Kobe, harbour and mountain', llegar: '≈ 25 min by train from Osaka',
    resumen: 'Japan\'s most open city: the country\'s oldest mosque, the foreign merchants\' houses, Chinatown and the harbour.',
    pasos: [
      { lugar: 'Your hotel in Osaka', que: 'I pick you up and we take the train to Sannomiya.' },
      { lugar: 'Kobe Mosque', que: 'Built in 1935, the oldest in Japan: it survived the war and the 1995 earthquake. It can be visited respectfully, outside prayer times.' },
      { lugar: 'Kitano Ijinkan', que: 'The 19th-century houses of European merchants on the hillside, with views over the bay.' },
      { lugar: 'Nankinmachi', que: 'Chinatown: steamed buns and street food to eat as you walk.' },
      { lugar: 'Meriken Park', que: 'The red port tower and the earthquake memorial, a section of the quay left exactly as it was in 1995.' },
      { lugar: 'Harborland', que: 'A walk along the waterfront at sunset with the city and the mountains behind.' },
      { lugar: 'Shin-Kobe Ropeway', que: 'Up to the Nunobiki Herb Gardens with the bay lit up at dusk. Then back to Osaka.' },
    ],
    comer: 'There are restaurants serving halal-certified wagyu; I\'ll tell you which and you make the booking.',
    ojo: 'For the mosque: shoulders and legs covered, and women with a headscarf (they lend them there).',
  },
  hiroshima: {
    titulo: 'Hiroshima and Miyajima', llegar: '≈ 1 h 25 min by shinkansen from Osaka',
    resumen: 'In the morning, the city that chose peace. In the afternoon, the sacred island of the torii that floats on the sea at high tide.',
    pasos: [
      { lugar: 'Shin-Osaka', que: 'We meet at the station or at your hotel and take the shinkansen. I\'ll show you how to reserve seats.' },
      { lugar: 'Peace Memorial Park', que: 'The Atomic Bomb Dome, the cenotaph and the peace flame. Then the Memorial Museum: hard, but essential.' },
      { lugar: 'Hiroshima okonomiyaki', que: 'The local version, layered with noodles. We order it without pork if needed: it is cooked in front of you.' },
      { lugar: 'Ferry to Miyajima', que: 'Tram or train to the port and ten minutes on the ferry watching the great torii come closer.' },
      { lugar: 'Itsukushima Shrine', que: 'The shrine on stilts and the torii in the sea. At low tide you can walk to it; at high tide it floats.' },
      { lugar: 'Omotesandō and deer', que: 'The shopping street with momiji manjū (little cakes shaped like maple leaves) and the island\'s deer.' },
      { lugar: 'Back', que: 'Ferry and shinkansen back: in Osaka around 19:30.' },
    ],
    comer: 'Okonomiyaki, Miyajima oysters and momiji manjū. Some places make it without pork or with halal certification; I check beforehand for the day.',
    ojo: 'I check the tide table in advance and adjust the order so you see the torii at high water (or walk to it at low tide).',
  },
  fuji: {
    titulo: 'Mount Fuji from Hakone', llegar: '≈ 1 h 30 min from Tokyo (or 2 days from Osaka)',
    resumen: 'Volcano, lake and forest in one day: the steaming valley of Ōwakudani, a boat across Lake Ashi and the torii of Hakone Shrine with Fuji behind it.',
    pasos: [
      { lugar: 'Shinjuku, Tokyo', que: 'I pick you up at your hotel in Tokyo and we take the Romancecar train to Hakone-Yumoto.' },
      { lugar: 'Hakone mountain railway', que: 'A small train that zigzags up the mountain (in June, among hydrangeas), then a cable car to Sōunzan.' },
      { lugar: 'Ōwakudani', que: 'Ropeway over the volcanic valley: steam vents, the smell of sulphur and black eggs boiled in the hot spring water. On a clear day, Fuji straight ahead.' },
      { lugar: 'Lunch at Tōgendai', que: 'On the lakeshore. There is curry, noodles and pork-free options.' },
      { lugar: 'Boat across Lake Ashi', que: 'About 40 minutes to Moto-Hakone, with Fuji reflected in the water on clear days.' },
      { lugar: 'Hakone Shrine', que: 'The red torii standing in the lake and the avenue of centuries-old cedars on the old Tōkaidō road.' },
      { lugar: 'Back to Tokyo', que: 'Bus and Romancecar back to Shinjuku, around 18:30.' },
    ],
    comer: 'Simple mountain food: curry, soba and tofu. I\'ll tell you if a broth contains pork.',
    ojo: 'Fuji is shy: it shows best in winter and in the morning. If volcanic gas is high they close the ropeway and we change the order.',
  },
  tokio: {
    titulo: 'Tokyo in a day', llegar: '≈ 2 h 30 min by shinkansen from Osaka',
    resumen: 'From old Tokyo to the Tokyo of screens: Asakusa in the morning, the Meiji forest, Harajuku and the Shibuya crossing at dusk.',
    pasos: [
      { lugar: 'Tsukiji Outer Market', que: 'Market breakfast: sweet omelette, fruit, seafood. I pick you up at your hotel in Tokyo.' },
      { lugar: 'Sensō-ji, Asakusa', que: 'The Kaminarimon gate with its giant lantern, Nakamise street and the oldest temple in Tokyo.' },
      { lugar: 'Lunch', que: 'Tempura, noodles or sushi. If you need halal, Asakusa is one of the areas of Tokyo with the most certified restaurants.' },
      { lugar: 'Meiji Jingū', que: 'A forest of around 100,000 trees in the middle of the city and the great wooden torii.' },
      { lugar: 'Harajuku and Omotesandō', que: 'Takeshita Street, youth fashion and the architect-designed shops of Omotesandō.' },
      { lugar: 'Tokyo Camii', que: 'Optional: Japan\'s largest mosque, in Ottoman style, ten minutes from Shibuya.' },
      { lugar: 'Shibuya', que: 'The world\'s most famous crossing as the lights come on, and the statue of Hachikō.' },
    ],
    comer: 'Tokyo has everything. For halal, Asakusa and Shibuya; vegetarian options are easy too.',
    ojo: 'For Tokyo it\'s best if you stay there: I travel to your hotel and the guide\'s ticket goes into the quote.',
  },
  nagano: {
    titulo: 'Nagano and the snow monkeys', llegar: '≈ 1 h 20 min from Tokyo (or 3 h from Osaka)',
    resumen: 'A temple almost 1,400 years old with a pitch-dark corridor under the altar, and the macaques that bathe in hot springs in the middle of the forest.',
    pasos: [
      { lugar: 'Your hotel', que: 'I pick you up and we take the shinkansen to Nagano.' },
      { lugar: 'Zenkō-ji', que: 'The temple that welcomes everyone. We go down into the completely dark corridor under the altar to feel our way to "the key to paradise".' },
      { lugar: 'Shinshu soba', que: 'Nagano is buckwheat-noodle country. There is a vegetarian version of the broth.' },
      { lugar: 'On the way to Jigokudani', que: 'Train and bus to Yudanaka, then a thirty-minute walk along a flat path among cedars.' },
      { lugar: 'Jigokudani Snow Monkey Park', que: 'Japanese macaques bathe in the hot spring and groom each other a metre away from you. No touching and no staring.' },
      { lugar: 'Shibu Onsen', que: 'A bathing village with Edo-period wooden streets and lanterns at dusk.' },
      { lugar: 'Back', que: 'Bus and shinkansen back to your hotel.' },
    ],
    comer: 'Soba, mountain vegetables and oyaki (stuffed buns). Easy for vegetarians.',
    ojo: 'The monkeys are in the water mainly from December to March, with snow. In summer they are there but bathe less. In winter, boots with grip.',
  },
  fukuoka: {
    titulo: 'Fukuoka and Dazaifu', llegar: '≈ 2 h 30 min by shinkansen from Osaka',
    resumen: 'Japan\'s gateway to Asia: shrines from the samurai era, the lake in Ōhori Park and the riverside food stalls at night.',
    pasos: [
      { lugar: 'Shin-Osaka', que: 'We meet at the station, or at your hotel in Fukuoka if you are staying there.' },
      { lugar: 'Kushida Shrine', que: 'Hakata\'s shrine, with the giant floats of the Yamakasa festival on display all year.' },
      { lugar: 'Dazaifu Tenmangū', que: 'Thirty minutes by train. The shrine of the god of learning, with its plum garden and shopping street.' },
      { lugar: 'Lunch in Dazaifu', que: 'Freshly made umegae-mochi (rice cake filled with sweet bean paste) and udon noodles.' },
      { lugar: 'Ōhori Park and castle', que: 'A walk around the lake and up onto the walls of the old Fukuoka Castle.' },
      { lugar: 'Canal City and Nakasu', que: 'The shopping centre with a canal running through it and, as night falls, the yatai: food stalls by the river.' },
      { lugar: 'Back', que: 'Shinkansen back to Osaka, or to your hotel in Fukuoka.' },
    ],
    comer: 'Hakata ramen uses pork broth (tonkotsu); if you avoid it, I take you for halal or chicken ramen. At the yatai I ask for you.',
    ojo: 'If you do Hiroshima and Fukuoka, ideally make it two days with a night in Fukuoka: we plan it together.',
  },
}
