export const WHATSAPP = 'https://wa.me/34634193106'
export const WHATSAPP_NUMBER = '+34 634 193 106'
export const EMAIL = 'tony@kansaiguide.jp'

const u = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&q=85`

export const TOURS = [
  {
    id: 'osaka-food',
    route: 0,
    title: 'Osaka Food Circuit',
    subtitle: 'Street Food & Hidden Bars',
    duration: 'Half Day · 5h',
    price: '¥75,000',
    gradient: 'from-orange-900/80 via-red-800/60 to-rose-900/80',
    accent: '#FF6B35',
    badge: 'Best Value',
    emoji: '🍜',
    image: u('photo-1578469645742-46cae010e5d4'),
    imageHero: u('photo-1578469645742-46cae010e5d4') + '&w=1920',
    imageCard: u('photo-1578469645742-46cae010e5d4') + '&w=800&h=500',
    description: 'Dive into Osaka\'s soul through legendary street food at Kuromon Market, bubbling takoyaki in Dotonbori, and izakayas with no English menu and no tourist prices.',
    longDescription: 'Osaka\'s greatest secret is that the best food costs almost nothing — if you know where to look. Tony takes you to Kuromon Market before the crowds, where 200-year-old vendors slice wagyu on the spot. Deep into the back alleys of Shinsekai for kushikatsu done the old way. End the night at a standing tachinomi bar that opened in 1953 and has never needed a sign.',
    highlights: ['Kuromon Ichiba Market dawn run', 'Dotonbori takoyaki & okonomiyaki', 'Hidden izakaya (no English menu)', 'Shinsekai kushikatsu institution', 'Sake & craft beer local picks', 'Night street stall crawl'],
    includes: ['Private guide', 'Food tasting guidance', 'Transit navigation', 'IC card top-up', 'Zero tourist traps policy'],
    meetingPoint: 'Namba Station Exit 14',
    languages: ['EN', 'ES', 'РУ', 'CS', 'AR'],
  },
  {
    id: 'hidden-kyoto',
    route: 1,
    title: 'Hidden Kyoto',
    subtitle: 'Temples, Geisha & Secrets',
    duration: 'Full Day · 10h',
    price: '¥95,000',
    gradient: 'from-rose-900/80 via-red-800/60 to-orange-900/80',
    accent: '#E53030',
    badge: 'Most Popular',
    emoji: '⛩️',
    image: u('photo-1524413840807-0c3cb6fa808d'),
    imageHero: u('photo-1524413840807-0c3cb6fa808d') + '&w=1920',
    imageCard: u('photo-1524413840807-0c3cb6fa808d') + '&w=800&h=500',
    description: 'Fushimi Inari at dawn before the crowds. Gion at dusk as lanterns ignite. Nishiki Market at noon. The Kyoto that photographs can\'t contain — guided in 5 languages.',
    longDescription: 'Begin at Fushimi Inari before 6 AM — thousands of vermillion torii gates in absolute silence. Tony knows the upper trails most visitors never reach. Descend to Nishiki Market for pickles and fresh matcha. After lunch in a hidden machiya townhouse, walk Gion as dusk falls and lanterns glow. End with dinner at an eight-seat counter restaurant with no online presence.',
    highlights: ['Fushimi Inari at dawn (before crowds)', 'Secret upper mountain trails', 'Nishiki Market — "Kyoto Kitchen"', 'Hidden machiya townhouse lunch', 'Gion lantern walk at dusk', 'Eight-seat omakase dinner'],
    includes: ['Private guide all day', 'Transit navigation', 'IC card assistance', 'Restaurant bookings', 'Cultural deep-dive narration'],
    meetingPoint: 'Kyoto Station Central Exit',
    languages: ['EN', 'ES', 'РУ', 'CS', 'AR'],
  },
  {
    id: 'kobe-refined',
    route: 2,
    title: 'Kobe Refined',
    subtitle: 'Castle & Cosmopolitan',
    duration: 'Full Day · 9h',
    price: '¥85,000',
    gradient: 'from-slate-900/80 via-gray-800/60 to-zinc-900/80',
    accent: '#94A3B8',
    badge: 'UNESCO',
    emoji: '🥩',
    image: u('photo-1590559899731-a382839e5549'),
    imageHero: u('photo-1590559899731-a382839e5549') + '&w=1920',
    imageCard: u('photo-1590559899731-a382839e5549') + '&w=800&h=500',
    description: 'Himeji Castle — Japan\'s greatest surviving fortress. Then Kobe\'s cosmopolitan harbor for the dinner you\'ll talk about forever: authentic Kobe Wagyu teppanyaki.',
    longDescription: 'Himeji Castle has survived every war, fire and earthquake in Japan\'s history. Tony takes you inside the six-story keep. From Himeji, the shinkansen delivers you to Kobe — Japan\'s most international city. Walk Kitano district\'s 19th-century merchant houses, then sit down for marbled Kobe Wagyu cooked tableside by a teppanyaki master.',
    highlights: ['Himeji Castle interior (UNESCO)', 'Koko-en castle gardens', 'Kobe Kitano foreign quarter', 'Authentic Kobe Wagyu teppanyaki', 'Harbor at dusk', 'Sake brewery district walk'],
    includes: ['Private guide all day', 'Shinkansen assistance', 'Castle entry', 'Teppanyaki booking', 'Walking tour both cities'],
    meetingPoint: 'Shin-Osaka Station Bullet Train Gate',
    languages: ['EN', 'ES', 'РУ', 'CS', 'AR'],
  },
  {
    id: 'nara-sacred',
    route: 3,
    title: 'Nara Sacred Forest',
    subtitle: 'Ancient Capital · Sacred Deer',
    duration: 'Full Day · 8h',
    price: '¥98,000',
    gradient: 'from-green-900/80 via-emerald-800/60 to-teal-900/80',
    accent: '#22C55E',
    badge: 'Spiritual',
    emoji: '🦌',
    image: u('photo-1545569341-9eb8b30979d9'),
    imageHero: u('photo-1545569341-9eb8b30979d9') + '&w=1920',
    imageCard: u('photo-1545569341-9eb8b30979d9') + '&w=800&h=500',
    description: 'Walk Japan\'s first capital alongside 1,200 sacred deer roaming freely since 710 AD. Todai-ji\'s Great Buddha, 3,000 stone lanterns, and an Edo merchant quarter frozen in time.',
    longDescription: 'Nara\'s 1,200 deer have been considered divine messengers since 768 AD. Tony leads you through Kasuga Taisha at dawn, past the towering gate of Todai-ji to face the 15-meter Great Buddha. Lunch in a restaurant only locals know. In the afternoon, explore Naramachi — an Edo-period merchant quarter where nothing has changed in three centuries.',
    highlights: ['Kasuga Taisha dawn — 3,000 stone lanterns', 'Todai-ji Great Buddha (15m tall)', 'Free-roaming sacred deer', 'Naramachi Edo-period streets', 'Hidden local restaurant lunch', 'Isui-en traditional garden'],
    includes: ['Private guide all day', 'Transit from Kyoto/Osaka', 'Deer crackers', 'Temple entry fees', 'Cultural deep-dive narration'],
    meetingPoint: 'Kintetsu Nara Station Exit 2',
    languages: ['EN', 'ES', 'РУ', 'CS', 'AR'],
  },
  {
    id: 'koyasan',
    route: 4,
    title: 'Kōyasan Pilgrimage',
    subtitle: 'Sacred Mountain · Shingon Buddhism',
    duration: 'Full Day · 11h',
    price: '¥165,000',
    gradient: 'from-violet-900/80 via-purple-800/60 to-indigo-900/80',
    accent: '#8B5CF6',
    badge: 'Premium',
    emoji: '🏔️',
    image: u('photo-1528360983277-13d401cdc186'),
    imageHero: u('photo-1528360983277-13d401cdc186') + '&w=1920',
    imageCard: u('photo-1528360983277-13d401cdc186') + '&w=800&h=500',
    description: 'Ascend the sacred mountain of Kōyasan — home of Shingon Buddhism since 816 AD. Private monk audience, Buddhist temple cuisine, and the Okunoin Cemetery among 200,000 stone lanterns.',
    longDescription: 'Kōyasan sits 900 meters above the Kii Peninsula, accessible only by cable car through ancient cedar forest. Founded by monk Kūkai in 816 AD. Tony arranges a private audience with a monk, traditional shojin ryori at a centuries-old temple, and a lantern-lit walk through Okunoin at dusk where 200,000 grave markers disappear into mist.',
    highlights: ['Sacred cable car through cedar forest', 'Private monk audience', 'Shojin ryori temple cuisine', 'Okunoin cemetery at dusk — 200,000 lanterns', 'Garan sacred complex', 'Kongobuji Zen garden'],
    includes: ['Private guide all day', 'All transport arrangements', 'Temple meal included', 'Cable car tickets', 'Comprehensive spiritual context'],
    meetingPoint: 'Osaka Namba Station — Private Car',
    languages: ['EN', 'ES', 'РУ', 'CS', 'AR'],
  },
  {
    id: 'osaka-kyoto-grand',
    route: 5,
    title: 'Osaka × Kyoto Grand Day',
    subtitle: 'The Complete Kansai',
    duration: 'Full Day · 12h',
    price: '¥130,000',
    gradient: 'from-amber-900/80 via-yellow-800/60 to-orange-900/80',
    accent: '#D4A847',
    badge: 'Signature',
    emoji: '🏯',
    image: u('photo-1578469645742-46cae010e5d4'),
    imageHero: u('photo-1578469645742-46cae010e5d4') + '&w=1920',
    imageCard: u('photo-1578469645742-46cae010e5d4') + '&w=800&h=500',
    description: 'Ancient Kyoto temples at dawn, Nishiki Market at noon, bullet train to Osaka\'s electric Dotonbori at dusk. Two cities, two centuries, one legendary day.',
    longDescription: 'Dawn at Fushimi Inari before the crowds. The chaos and color of Nishiki Market. A hidden machiya lunch. Then the shinkansen to Osaka\'s kinetic energy — Dotonbori street food with Tony pointing out which stalls opened in 1902. The day ends at a rooftop bar with Osaka Castle illuminated below.',
    highlights: ['Fushimi Inari at absolute dawn', 'Nishiki Market food circuit', 'Hidden machiya lunch', 'Shinkansen city switch', 'Dotonbori street food tour', 'Osaka Castle rooftop view at night'],
    includes: ['Private guide 12h', 'All transit navigation', 'IC card top-up', 'Both city restaurant bookings', 'Cultural narrative both cities'],
    meetingPoint: 'Kyoto Station Central Exit',
    languages: ['EN', 'ES', 'РУ', 'CS', 'AR'],
  },
  {
    id: 'mountain-hiking',
    route: 6,
    title: 'Mountain Hiking',
    subtitle: 'Kurama · Ancient Pilgrimage Trails',
    duration: 'Full Day · 9h',
    price: '¥108,000',
    gradient: 'from-emerald-900/80 via-teal-800/60 to-cyan-900/80',
    accent: '#10B981',
    badge: 'Adventure',
    emoji: '⛰️',
    image: u('photo-1448375240586-882707db888b'),
    imageHero: u('photo-1448375240586-882707db888b') + '&w=1920',
    imageCard: u('photo-1448375240586-882707db888b') + '&w=800&h=500',
    description: 'Walk the same mountain trails emperors walked seeking enlightenment. Cedar forests, moss-covered lanterns, mountain shrines, and a hidden waterfall on no map.',
    longDescription: 'The Kurama mountain trail north of Kyoto was walked by emperors seeking clarity — cedar forests, stone lanterns swallowed by moss, shrines smelling of centuries of incense. Tony walks the full trail, narrating the folklore of each landmark. Descend through Arashiyama\'s bamboo groves to a hidden waterfall meditation spot. End with a traditional tea ceremony in a garden overlooking the hills you just crossed.',
    highlights: ['Kurama pilgrimage trail — imperial route', 'Ancient cedar shrine forest', 'Hidden waterfall meditation spot', 'Arashiyama bamboo grove (off-hour)', 'Traditional tea ceremony in nature', 'Monkey park optional stop'],
    includes: ['Private guide all day', 'Trail navigation & safety', 'Forest shrine ritual explanation', 'Tea ceremony included', 'Packed snack recommendations'],
    meetingPoint: 'Kurama Station Exit',
    languages: ['EN', 'ES', 'РУ', 'CS', 'AR'],
  },
]

export const PRICING = [
  {
    id: 'essential',
    name: 'Essential',
    subtitle: 'Half Day',
    price: '¥75,000',
    priceUSD: '≈ $500',
    duration: '4–5 hours',
    features: ['Up to 4 guests', 'One city or area', 'Transit assistance', 'Flexible route', 'All 5 languages'],
    cta: 'Book Essential',
    hot: false,
  },
  {
    id: 'signature',
    name: 'Signature',
    subtitle: 'Full Day',
    price: '¥95,000–¥130,000',
    priceUSD: '≈ $635–$870',
    duration: '8–12 hours',
    features: ['Up to 6 guests', 'Multiple areas', 'Private transport option', 'Lunch recommendation', 'Cultural deep-dives', 'Evening extension option'],
    cta: 'Book Signature',
    hot: true,
  },
  {
    id: 'premium',
    name: 'Premium',
    subtitle: 'Kōyasan / Multi-Day',
    price: '¥165,000',
    priceUSD: '≈ $1,100',
    duration: 'Full day or multi-day',
    features: ['Unlimited guests', 'All Kansai region', 'Full itinerary design', 'Private transport', 'Restaurant reservations', 'Priority WhatsApp', '24h availability'],
    cta: 'Book Premium',
    hot: false,
  },
]

export const FAQS = [
  { q: 'Are tours truly private?', a: '100% private — your booking is exclusively yours. No other groups, no shared coaches. Just you and Tony with full attention on your experience.' },
  { q: 'How far in advance should I book?', a: 'Tony recommends 2–3 weeks ahead for weekends and peak seasons (March–May cherry blossom, October–November autumn). Weekday slots often available 1 week out.' },
  { q: 'What is the cancellation policy?', a: 'Full refund 72+ hours before the tour. 50% refund within 48 hours. No refund within 24 hours. Tony is flexible with reschedules — just reach out via WhatsApp.' },
  { q: 'Is transport included?', a: 'Tony assists with all transit navigation and IC card top-up. Private vehicle available for Premium package. Public transit is used for the authentic local experience.' },
  { q: 'Which languages does Tony guide in?', a: 'English, Spanish, Russian, Czech, and Arabic — all at native-level proficiency. No broken phrases, just natural conversation.' },
  { q: 'Can Tony help with restaurant reservations?', a: 'Absolutely. Tony has relationships with local restaurants including hidden spots that don\'t appear on any app. He pre-books in advance and pre-orders special dishes.' },
  { q: 'What areas does Tony cover?', a: 'Tony covers the full Kansai region: Osaka, Kyoto, Nara, Kobe, Himeji, Arashiyama, Kurama, Fushimi, Kōyasan, and more.' },
]

export const STATS = [
  { value: '7', label: 'Destinations', icon: '📍' },
  { value: '400+', label: 'Tours Completed', icon: '⭐' },
  { value: '5', label: 'Languages', icon: '🌐' },
  { value: '100%', label: 'Private', icon: '🔒' },
]

const gu = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&q=85&w=600&h=600`

export const GUIDES = [
  {
    id: 'tony',
    name: 'Tony Hanma',
    role: 'Head Guide · Osaka',
    since: '2018',
    tours: '200+',
    rating: '5.0',
    photo: gu('photo-1507003211169-0a1dd7228f2d'),
    accent: '#E53030',
    languages: ['🇬🇧', '🇪🇸', '🇷🇺', '🇨🇿', '🇸🇦'],
    langLabels: ['EN', 'ES', 'RU', 'CS', 'AR'],
    specialty: 'Food, Culture & History',
    bio: "The original Kansai insider. Tony built this company from his personal obsession with Osaka's hidden izakayas, Kyoto's secret temples, and the living stories behind every stone in the region.",
    highlights: ['Osaka Food Circuit', 'Hidden Kyoto', 'Osaka × Kyoto Grand Day'],
  },
  {
    id: 'johnny',
    name: 'Johnny Coleta',
    role: 'Senior Guide · Kyoto',
    since: '2020',
    tours: '120+',
    rating: '5.0',
    photo: gu('photo-1506794778202-cad84cf45f1d'),
    accent: '#FF6B35',
    languages: ['🇬🇧', '🇪🇸', '🇫🇷'],
    langLabels: ['EN', 'ES', 'FR'],
    specialty: 'Architecture & Urban Secrets',
    bio: "Johnny's eye for architecture and urban design transforms every city walk into a visual masterclass. He knows every machiya townhouse in Kyoto and which alley hides the best ramen counter in Namba.",
    highlights: ['Hidden Kyoto', 'Kobe Refined', 'Nara Sacred Forest'],
  },
  {
    id: 'larion',
    name: 'Larion',
    role: 'Nature & Spiritual Guide',
    since: '2021',
    tours: '85+',
    rating: '5.0',
    photo: gu('photo-1472099645785-5658abf4ff4e'),
    accent: '#8B5CF6',
    languages: ['🇬🇧', '🇷🇺', '🇨🇿'],
    langLabels: ['EN', 'RU', 'CS'],
    specialty: 'Mountains, Temples & Pilgrimage',
    bio: 'Larion discovered Japan through its ancient pilgrimage trails and never left. His Kōyasan tour has been called life-changing by guests from six continents. He knows where the monks meditate before dawn.',
    highlights: ['Kōyasan Pilgrimage', 'Mountain Hiking', 'Nara Sacred Forest'],
  },
]

export const TESTIMONIALS = [
  {
    name: 'Sofía R.',
    country: 'Spain 🇪🇸',
    tour: 'Hidden Kyoto',
    rating: 5,
    text: 'Tony nos llevó a lugares que ni sabíamos que existían. Fushimi Inari al amanecer, sin nadie más — fue mágico. El mejor día de todo nuestro viaje a Japón.',
  },
  {
    name: 'James K.',
    country: 'UK 🇬🇧',
    tour: 'Kōyasan Pilgrimage',
    rating: 5,
    text: 'Larion arranged a private meeting with a monk that I will never forget. The lantern walk through Okunoin at dusk was genuinely spiritual. Completely unforgettable.',
  },
  {
    name: 'Алексей В.',
    country: 'Russia 🇷🇺',
    tour: 'Osaka Food Circuit',
    rating: 5,
    text: 'Тони знает каждый переулок Осаки. Мы попробовали блюда, которых не найдёшь ни в одном путеводителе. Лучший гид, которого я встречал в жизни.',
  },
  {
    name: 'Markéta H.',
    country: 'Czech Republic 🇨🇿',
    tour: 'Mountain Hiking',
    rating: 5,
    text: 'Johnny nás provedl trasami, kde nebyl jediný turista. Arashijamský bambusový háj v pět ráno — absolutní tišina. Tohle zažít nejde jinak než soukromě.',
  },
  {
    name: 'Omar A.',
    country: 'UAE 🇦🇪',
    tour: 'Osaka × Kyoto Grand Day',
    rating: 5,
    text: 'Tony speaks perfect Arabic and made us feel at home throughout Japan. His knowledge of halal options and cultural sensitivities made this trip truly comfortable for our family.',
  },
]

export const LANGUAGES = [
  { flag: '🇬🇧', name: 'English', code: 'EN' },
  { flag: '🇪🇸', name: 'Spanish', code: 'ES' },
  { flag: '🇷🇺', name: 'Russian', code: 'РУ' },
  { flag: '🇨🇿', name: 'Czech', code: 'CS' },
  { flag: '🇸🇦', name: 'Arabic', code: 'AR' },
]
