export const WHATSAPP = 'https://wa.me/34634193106'
export const WHATSAPP_NUMBER = '+34 634 193 106'
export const EMAIL = 'tony@kansaiguide.jp'

const u = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&q=85`

export const TOURS = [
  {
    id: 'osaka-kyoto',
    title: 'Osaka & Kyoto',
    subtitle: 'City Experience',
    duration: 'Full Day · 10h',
    price: '¥68,000',
    gradient: 'from-rose-900/80 via-red-800/60 to-orange-900/80',
    accent: '#E53030',
    badge: 'Most Popular',
    emoji: '🏯',
    image: u('photo-1578469645742-46cae010e5d4'),
    imageHero: u('photo-1578469645742-46cae010e5d4') + '&w=1920',
    imageCard: u('photo-1578469645742-46cae010e5d4') + '&w=800&h=500',
    description: 'Dive into the urban soul of Japan. Skip tourist crowds and discover the hidden alleys, secret shrines, and authentic flavors that locals treasure.',
    longDescription: 'Begin the day at dawn in Fushimi Inari before the crowds arrive — thousands of vermillion torii gates leading up a sacred mountain, just you and the birdsong. Then descend into Kyoto\'s Nishiki Market, where 400-year-old vendors still sell the same pickles and fish their great-grandparents did. After lunch in a hidden machiya townhouse, take the train to Osaka for Dotonbori street food with Tony guiding each bite and its story. End the evening at a standing izakaya that has no English menu and no tourist prices.',
    highlights: [
      'Fushimi Inari at dawn (before crowds)',
      'Nishiki Market — the "Kyoto Kitchen"',
      'Hidden machiya townhouse lunch',
      'Dotonbori street food tour',
      'Local izakaya dinner (no English menu)',
      'Gion evening walk',
    ],
    includes: ['Private guide all day', 'Transit navigation', 'IC card top-up assistance', 'Restaurant bookings', 'Cultural commentary'],
    meetingPoint: 'Kyoto Station Central Exit',
    languages: ['EN', 'ES', 'РУ', 'CS', 'AR'],
  },
  {
    id: 'trails-peaks',
    title: 'Trails & Peaks',
    subtitle: 'Mountain & Nature',
    duration: 'Full Day · 9h',
    price: '¥68,000',
    gradient: 'from-emerald-900/80 via-teal-800/60 to-cyan-900/80',
    accent: '#10B981',
    badge: 'Adventure',
    emoji: '⛰️',
    image: u('photo-1448375240586-882707db888b'),
    imageHero: u('photo-1448375240586-882707db888b') + '&w=1920',
    imageCard: u('photo-1448375240586-882707db888b') + '&w=800&h=500',
    description: 'Escape into Japan\'s sacred wilderness. Walk ancient pilgrimage routes, breathe mountain air, and find the spiritual calm that has drawn seekers for centuries.',
    longDescription: 'The Kurama mountain trail north of Kyoto was walked by emperors seeking enlightenment. Today it remains largely unchanged — cedar forests, moss-covered stone lanterns, mountain shrines smelling of incense. Tony walks the full trail with you, sharing the folklore of each landmark. Descend through the bamboo groves of Arashiyama, stopping at a hidden waterfall meditation spot that no guidebook mentions. The day ends with a traditional tea ceremony performed in a garden that overlooks the hills you just crossed.',
    highlights: [
      'Kurama mountain pilgrimage trail',
      'Ancient cedar forest shrines',
      'Hidden waterfall meditation spot',
      'Arashiyama bamboo grove (off-hour)',
      'Traditional tea ceremony in nature',
      'Monkey park optional stop',
    ],
    includes: ['Private guide all day', 'Trail navigation', 'Forest shrine rituals explanation', 'Tea ceremony included', 'Packed snack recommendation'],
    meetingPoint: 'Kurama Station Exit',
    languages: ['EN', 'ES', 'РУ', 'CS', 'AR'],
  },
  {
    id: 'nara-sacred',
    title: 'Nara Sacred Deer',
    subtitle: 'Ancient Capital',
    duration: 'Full Day · 8h',
    price: '¥68,000',
    gradient: 'from-green-900/80 via-emerald-800/60 to-teal-900/80',
    accent: '#22C55E',
    badge: 'Spiritual',
    emoji: '🦌',
    image: u('photo-1545569341-9eb8b30979d9'),
    imageHero: u('photo-1545569341-9eb8b30979d9') + '&w=1920',
    imageCard: u('photo-1545569341-9eb8b30979d9') + '&w=800&h=500',
    description: 'Walk through Japan\'s oldest capital alongside sacred deer that roam freely since the 8th century. Todai-ji\'s Great Buddha waits at the end of a lantern-lit path.',
    longDescription: 'Nara was Japan\'s first permanent capital — established in 710 AD, its streets have barely changed. Today over 1,200 deer roam freely through Nara Park, considered divine messengers. Tony leads you through Kasuga Taisha shrine at dawn when stone lanterns still flicker, past the towering gate of Todai-ji to stand face to face with the 15-meter Great Buddha. Lunch is in a hidden restaurant behind the park that only locals know. In the afternoon, explore Naramachi — an Edo-period merchant quarter frozen in time.',
    highlights: [
      'Kasuga Taisha at dawn — 3,000 stone lanterns',
      'Todai-ji Great Buddha (15m tall)',
      'Free-roaming sacred deer',
      'Naramachi Edo-period streets',
      'Hidden local restaurant lunch',
      'Isui-en traditional garden',
    ],
    includes: ['Private guide all day', 'Transit from Kyoto/Osaka', 'Deer crackers included', 'Temple entry fees', 'Cultural deep-dive narration'],
    meetingPoint: 'Kintetsu Nara Station Exit 2',
    languages: ['EN', 'ES', 'РУ', 'CS', 'AR'],
  },
  {
    id: 'himeji-kobe',
    title: 'Himeji Castle & Kobe',
    subtitle: 'Castle & Cosmopolitan',
    duration: 'Full Day · 10h',
    price: '¥68,000',
    gradient: 'from-slate-900/80 via-gray-800/60 to-zinc-900/80',
    accent: '#94A3B8',
    badge: 'UNESCO',
    emoji: '🏰',
    image: u('photo-1590559899731-a382839e5549'),
    imageHero: u('photo-1590559899731-a382839e5549') + '&w=1920',
    imageCard: u('photo-1590559899731-a382839e5549') + '&w=800&h=500',
    description: 'Stand beneath the White Heron Castle — Japan\'s most spectacular UNESCO fortress — then descend to Kobe\'s cosmopolitan harbor for the country\'s finest Wagyu beef.',
    longDescription: 'Himeji Castle has never been destroyed by war, fire, or earthquake — a miracle of survival that its immaculate white towers embody. Tony takes you inside the six-story keep, explaining the samurai-era engineering that has withstood centuries. Cherry blossoms frame the castle in spring; autumn turns its gardens crimson. From Himeji, take the shinkansen to Kobe — Japan\'s most international city. Walk the Kitano district of 19th-century foreign merchant houses, then sit down for the dinner you\'ll talk about for years: authentic Kobe Wagyu teppanyaki.',
    highlights: [
      'Himeji Castle interior (UNESCO World Heritage)',
      'Koko-en castle gardens',
      'Kobe Kitano foreign quarter',
      'Authentic Kobe Wagyu teppanyaki dinner',
      'Harbor view at dusk',
      'Sake brewery district walk',
    ],
    includes: ['Private guide all day', 'Train tickets assistance', 'Castle entry', 'Teppanyaki restaurant booking', 'Walking tour both cities'],
    meetingPoint: 'Shin-Osaka Station Bullet Train Gate',
    languages: ['EN', 'ES', 'РУ', 'CS', 'AR'],
  },
  {
    id: 'arashiyama',
    title: 'Arashiyama Bamboo',
    subtitle: 'Forest & Temples',
    duration: 'Half Day · 5h',
    price: '¥55,000',
    gradient: 'from-lime-900/80 via-green-800/60 to-emerald-900/80',
    accent: '#84CC16',
    badge: 'Iconic',
    emoji: '🎋',
    image: u('photo-1524413840807-0c3cb6fa808d'),
    imageHero: u('photo-1524413840807-0c3cb6fa808d') + '&w=1920',
    imageCard: u('photo-1524413840807-0c3cb6fa808d') + '&w=800&h=500',
    description: 'Enter one of the world\'s most photographed places — Arashiyama\'s towering bamboo grove — at the hour when light turns the trunks gold and the crowds haven\'t yet arrived.',
    longDescription: 'Tony meets you at 6:30 AM at Tenryu-ji temple gate — before the tour buses arrive. The bamboo grove at this hour is otherworldly: shafts of early light filtering through 20-meter stalks, the hollow sound of wind moving through them like music. From there, a hidden path leads to Jojakko-ji temple on the hillside — mossy, quiet, appearing in no itinerary. At the bamboo boat pier, Tony has arranged a traditional river punting experience as the morning mist still drifts over the Oi River.',
    highlights: [
      'Arashiyama Bamboo Grove at dawn',
      'Tenryu-ji Zen garden (UNESCO)',
      'Hidden hillside Jojakko-ji temple',
      'Traditional river punting boat',
      'Kimono rental optional (booked in advance)',
      'Matcha and wagashi in a riverside teahouse',
    ],
    includes: ['Private guide', 'Temple entry fees', 'River boat experience', 'Matcha at teahouse', 'Photography guidance'],
    meetingPoint: 'Arashiyama Bamboo Grove North Entrance',
    languages: ['EN', 'ES', 'РУ', 'CS', 'AR'],
  },
  {
    id: 'multi-language',
    title: 'Your Own Japan',
    subtitle: 'Fully Custom · Any Area',
    duration: 'Half Day or Full Day',
    price: 'From ¥55,000',
    gradient: 'from-amber-900/80 via-yellow-800/60 to-orange-900/80',
    accent: '#D4A847',
    badge: '5 Languages',
    emoji: '🌏',
    image: u('photo-1528360983277-13d401cdc186'),
    imageHero: u('photo-1528360983277-13d401cdc186') + '&w=1920',
    imageCard: u('photo-1528360983277-13d401cdc186') + '&w=800&h=500',
    description: 'Tell Tony what you love. He builds an entire day around it — in your language. Food obsessive, architecture nerd, anime fan, photographer: your interests write the itinerary.',
    longDescription: 'Language shapes how we understand a place. When Tony guides in your native tongue — whether English, Spanish, Russian, Czech, or Arabic — the experience changes completely. Subtle humor, untranslatable concepts, and the true emotional weight of history all come through. This tour is fully customizable: tell Tony your interests (food, architecture, history, anime, nature, photography) and he builds the day around you. Completely private, completely personal.',
    highlights: [
      'Fully customizable itinerary',
      'Guided in EN · ES · РУ · CS · AR',
      'Any area of Kansai',
      'Solo, couples, or groups',
      'Flexible start/end times',
      'Insider recommendations only',
    ],
    includes: ['Private guide', 'Flexible route', 'All ages welcome', 'Custom pace', 'WhatsApp planning support'],
    meetingPoint: 'Agreed upon booking',
    languages: ['EN', 'ES', 'РУ', 'CS', 'AR'],
  },
]

export const PRICING = [
  {
    id: 'essential',
    name: 'Essential',
    subtitle: 'Half Day',
    price: '¥55,000',
    priceUSD: '≈ $370',
    duration: '4–5 hours',
    features: ['Up to 4 guests', 'One city or area', 'Transit assistance', 'Flexible route', 'All 5 languages'],
    cta: 'Book Essential',
    hot: false,
  },
  {
    id: 'signature',
    name: 'Signature',
    subtitle: 'Full Day',
    price: '¥68,000',
    priceUSD: '≈ $455',
    duration: '8–10 hours',
    features: ['Up to 6 guests', 'Multiple areas', 'Private transport option', 'Lunch recommendation', 'Cultural deep-dives', 'Evening extension option'],
    cta: 'Book Signature',
    hot: true,
  },
  {
    id: 'premium',
    name: 'Premium',
    subtitle: 'Multi-Day',
    price: '¥120,000',
    priceUSD: '≈ $800',
    duration: '2+ full days',
    features: ['Unlimited guests', 'All Kansai region', 'Full itinerary design', 'Private transport', 'Restaurant reservations', 'Priority WhatsApp support', '24h availability'],
    cta: 'Book Premium',
    hot: false,
  },
]

export const FAQS = [
  { q: 'Are tours truly private?', a: 'Yes — 100% private. Your booking is exclusively yours. No other groups, no shared coaches. Just you and Tony with full attention on your experience.' },
  { q: 'How far in advance should I book?', a: 'Tony recommends booking 2–3 weeks ahead for weekends and peak seasons (March–May cherry blossom, October–November autumn). Weekday slots are often available 1 week out.' },
  { q: 'What is the cancellation policy?', a: 'Full refund for cancellations 72+ hours before the tour. 50% refund within 48 hours. No refund within 24 hours. Tony is flexible with reschedules — just reach out via WhatsApp.' },
  { q: 'Is transport included?', a: 'Tony assists with all transit navigation and IC card top-up. Private vehicle options are available for Signature and Premium packages. Public transit is used for the authentic local experience.' },
  { q: 'Which languages does Tony guide in?', a: 'Tony guides fluently in English, Spanish, Russian, Czech, and Arabic — all at native-level proficiency. No broken phrases, no confusion, just natural conversation.' },
  { q: 'Can Tony help with restaurant reservations?', a: 'Absolutely. Tony has relationships with local restaurants — including hidden spots that don\'t appear on any app. He can book in advance and even pre-order special dishes for you.' },
  { q: 'What areas does Tony cover?', a: 'Tony covers the full Kansai region: Osaka, Kyoto, Nara, Kobe, Himeji, Arashiyama, Kurama, Fushimi, and more. Multi-day tours can extend further.' },
]

export const STATS = [
  { value: '6', label: 'Destinations', icon: '📍' },
  { value: '200+', label: 'Tours Completed', icon: '⭐' },
  { value: '5', label: 'Languages', icon: '🌐' },
  { value: '100%', label: 'Private', icon: '🔒' },
]

export const LANGUAGES = [
  { flag: '🇬🇧', name: 'English', code: 'EN' },
  { flag: '🇪🇸', name: 'Spanish', code: 'ES' },
  { flag: '🇷🇺', name: 'Russian', code: 'РУ' },
  { flag: '🇨🇿', name: 'Czech', code: 'CS' },
  { flag: '🇸🇦', name: 'Arabic', code: 'AR' },
]
