export const WHATSAPP = 'https://wa.me/34634193106'
export const WHATSAPP_NUMBER = '+34 634 193 106'
export const EMAIL = 'tony@kansaiguide.jp'

const u = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&q=85`

export const TOURS = [
  {
    id: 'osaka-food',
    route: 0,
    title: 'Osaka Food Circuit',
    subtitle: 'Street Food & Hidden Bars',
    duration: 'Half Day · 5h',
    price: '¥75,000',
    gradient: 'from-orange-900/80 via-red-800/60 to-rose-900/80',
    accent: '#FF6B35',
    badge: 'Best Value',
    emoji: '🍜',
    image: u('photo-1578469645742-46cae010e5d4'),
    imageHero: u('photo-1578469645742-46cae010e5d4') + '&w=1920',
    imageCard: u('photo-1578469645742-46cae010e5d4') + '&w=800&h=500',
    description: 'Dive into Osaka\'s soul through legendary street food at Kuromon Market, bubbling takoyaki in Dotonbori, and izakayas with no English menu and no tourist prices.',
    longDescription: 'Osaka\'s greatest secret is that the best food costs almost nothing — if you know where to look. Tony takes you to Kuromon Market before the crowds, where 200-year-old vendors slice wagyu on the spot. Deep into the back alleys of Shinsekai for kushikatsu done the old way. End the night at a standing tachinomi bar that opened in 1953 and has never needed a sign.',
    highlights: ['Kuromon Ichiba Market dawn run', 'Dotonbori takoyaki & okonomiyaki', 'Hidden izakaya (no English menu)', 'Shinsekai kushikatsu institution', 'Sake & craft beer local picks', 'Night street stall crawl'],
    includes: ['Private guide', 'Food tasting guidance', 'Transit navigation', 'IC card top-up', 'Zero tourist traps policy'],
    meetingPoint: 'Namba Station Exit 14',
    mapStops: [
      { name: 'Namba Station', lat: 34.6688, lng: 135.4963 },
      { name: 'Kuromon Ichiba Market', lat: 34.6684, lng: 135.5060 },
      { name: 'Dotonbori', lat: 34.6687, lng: 135.5013 },
      { name: 'Shinsekai', lat: 34.6526, lng: 135.5063 },
    ],
    languages: ['EN', 'ES', 'РУ', 'CS', 'AR'],
  },
  {
    id: 'hidden-kyoto',
    route: 1,
    title: 'Hidden Kyoto',
    subtitle: 'Temples, Geisha & Secrets',
    duration: 'Full Day · 10h',
    price: '¥95,000',
    gradient: 'from-rose-900/80 via-red-800/60 to-orange-900/80',
    accent: '#E53030',
    badge: 'Most Popular',
    emoji: '⛩️',
    image: u('photo-1524413840807-0c3cb6fa808d'),
    imageHero: u('photo-1524413840807-0c3cb6fa808d') + '&w=1920',
    imageCard: u('photo-1524413840807-0c3cb6fa808d') + '&w=800&h=500',
    description: 'Fushimi Inari at dawn before the crowds. Gion at dusk as lanterns ignite. Nishiki Market at noon. The Kyoto that photographs can\'t contain — guided in 5 languages.',
    longDescription: 'Begin at Fushimi Inari before 6 AM — thousands of vermillion torii gates in absolute silence. Tony knows the upper trails most visitors never reach. Descend to Nishiki Market for pickles and fresh matcha. After lunch in a hidden machiya townhouse, walk Gion as dusk falls and lanterns glow. End with dinner at an eight-seat counter restaurant with no online presence.',
    highlights: ['Fushimi Inari at dawn (before crowds)', 'Secret upper mountain trails', 'Nishiki Market — "Kyoto Kitchen"', 'Hidden machiya townhouse lunch', 'Gion lantern walk at dusk', 'Eight-seat omakase dinner'],
    includes: ['Private guide all day', 'Transit navigation', 'IC card assistance', 'Restaurant bookings', 'Cultural deep-dive narration'],
    meetingPoint: 'Kyoto Station Central Exit',
    mapStops: [
      { name: 'Kyoto Station', lat: 34.9859, lng: 135.7588 },
      { name: 'Fushimi Inari Taisha', lat: 34.9671, lng: 135.7727 },
      { name: 'Nishiki Market', lat: 35.0051, lng: 135.7659 },
      { name: 'Gion', lat: 35.0038, lng: 135.7755 },
    ],
    languages: ['EN', 'ES', 'РУ', 'CS', 'AR'],
  },
  {
    id: 'kobe-refined',
    route: 2,
    title: 'Kobe Refined',
    subtitle: 'Castle & Cosmopolitan',
    duration: 'Full Day · 9h',
    price: '¥85,000',
    gradient: 'from-slate-900/80 via-gray-800/60 to-zinc-900/80',
    accent: '#94A3B8',
    badge: 'UNESCO',
    emoji: '🥩',
    image: u('photo-1590559899731-a382839e5549'),
    imageHero: u('photo-1590559899731-a382839e5549') + '&w=1920',
    imageCard: u('photo-1590559899731-a382839e5549') + '&w=800&h=500',
    description: 'Himeji Castle — Japan\'s greatest surviving fortress. Then Kobe\'s cosmopolitan harbor for the dinner you\'ll talk about forever: authentic Kobe Wagyu teppanyaki.',
    longDescription: 'Himeji Castle has survived every war, fire and earthquake in Japan\'s history. Tony takes you inside the six-story keep. From Himeji, the shinkansen delivers you to Kobe — Japan\'s most international city. Walk Kitano district\'s 19th-century merchant houses, then sit down for marbled Kobe Wagyu cooked tableside by a teppanyaki master.',
    highlights: ['Himeji Castle interior (UNESCO)', 'Koko-en castle gardens', 'Kobe Kitano foreign quarter', 'Authentic Kobe Wagyu teppanyaki', 'Harbor at dusk', 'Sake brewery district walk'],
    includes: ['Private guide all day', 'Shinkansen assistance', 'Castle entry', 'Teppanyaki booking', 'Walking tour both cities'],
    meetingPoint: 'Shin-Osaka Station Bullet Train Gate',
    mapStops: [
      { name: 'Shin-Osaka Station', lat: 34.7333, lng: 135.5000 },
      { name: 'Himeji Castle', lat: 34.8394, lng: 134.6939 },
      { name: 'Kitano-cho, Kobe', lat: 34.7020, lng: 135.1894 },
      { name: 'Meriken Park', lat: 34.6878, lng: 135.1903 },
    ],
    languages: ['EN', 'ES', 'РУ', 'CS', 'AR'],
  },
  {
    id: 'nara-sacred',
    route: 3,
    title: 'Nara Sacred Forest',
    subtitle: 'Ancient Capital · Sacred Deer',
    duration: 'Full Day · 8h',
    price: '¥98,000',
    gradient: 'from-green-900/80 via-emerald-800/60 to-teal-900/80',
    accent: '#22C55E',
    badge: 'Spiritual',
    emoji: '🦌',
    image: u('photo-1545569341-9eb8b30979d9'),
    imageHero: u('photo-1545569341-9eb8b30979d9') + '&w=1920',
    imageCard: u('photo-1545569341-9eb8b30979d9') + '&w=800&h=500',
    description: 'Walk Japan\'s first capital alongside 1,200 sacred deer roaming freely since 710 AD. Todai-ji\'s Great Buddha, 3,000 stone lanterns, and an Edo merchant quarter frozen in time.',
    longDescription: 'Nara\'s 1,200 deer have been considered divine messengers since 768 AD. Tony leads you through Kasuga Taisha at dawn, past the towering gate of Todai-ji to face the 15-meter Great Buddha. Lunch in a restaurant only locals know. In the afternoon, explore Naramachi — an Edo-period merchant quarter where nothing has changed in three centuries.',
    highlights: ['Kasuga Taisha dawn — 3,000 stone lanterns', 'Todai-ji Great Buddha (15m tall)', 'Free-roaming sacred deer', 'Naramachi Edo-period streets', 'Hidden local restaurant lunch', 'Isui-en traditional garden'],
    includes: ['Private guide all day', 'Transit from Kyoto/Osaka', 'Deer crackers', 'Temple entry fees', 'Cultural deep-dive narration'],
    meetingPoint: 'Kintetsu Nara Station Exit 2',
    mapStops: [
      { name: 'Kintetsu Nara Station', lat: 34.6857, lng: 135.8247 },
      { name: 'Kasuga Grand Shrine', lat: 34.6813, lng: 135.8449 },
      { name: 'Tōdai-ji Temple', lat: 34.6888, lng: 135.8399 },
      { name: 'Naramachi', lat: 34.6780, lng: 135.8306 },
    ],
    languages: ['EN', 'ES', 'РУ', 'CS', 'AR'],
  },
  {
    id: 'koyasan',
    route: 4,
    title: 'Kōyasan Pilgrimage',
    subtitle: 'Sacred Mountain · Shingon Buddhism',
    duration: 'Full Day · 11h',
    price: '¥165,000',
    gradient: 'from-violet-900/80 via-purple-800/60 to-indigo-900/80',
    accent: '#8B5CF6',
    badge: 'Premium',
    emoji: '🏔️',
    image: u('photo-1528360983277-13d401cdc186'),
    imageHero: u('photo-1528360983277-13d401cdc186') + '&w=1920',
    imageCard: u('photo-1528360983277-13d401cdc186') + '&w=800&h=500',
    description: 'Ascend the sacred mountain of Kōyasan — home of Shingon Buddhism since 816 AD. Private monk audience, Buddhist temple cuisine, and the Okunoin Cemetery among 200,000 stone lanterns.',
    longDescription: 'Kōyasan sits 900 meters above the Kii Peninsula, accessible only by cable car through ancient cedar forest. Founded by monk Kūkai in 816 AD. Tony arranges a private audience with a monk, traditional shojin ryori at a centuries-old temple, and a lantern-lit walk through Okunoin at dusk where 200,000 grave markers disappear into mist.',
    highlights: ['Sacred cable car through cedar forest', 'Private monk audience', 'Shojin ryori temple cuisine', 'Okunoin cemetery at dusk — 200,000 lanterns', 'Garan sacred complex', 'Kongobuji Zen garden'],
    includes: ['Private guide all day', 'All transport arrangements', 'Temple meal included', 'Cable car tickets', 'Comprehensive spiritual context'],
    meetingPoint: 'Osaka Namba Station — Private Car',
    mapStops: [
      { name: 'Namba, Osaka', lat: 34.6688, lng: 135.4963 },
      { name: 'Kōyasan', lat: 34.2136, lng: 135.5851 },
      { name: 'Kongobuji Temple', lat: 34.2134, lng: 135.5839 },
      { name: 'Okunoin Cemetery', lat: 34.2175, lng: 135.5943 },
    ],
    languages: ['EN', 'ES', 'РУ', 'CS', 'AR'],
  },
  {
    id: 'osaka-kyoto-grand',
    route: 5,
    title: 'Osaka × Kyoto Grand Day',
    subtitle: 'The Complete Kansai',
    duration: 'Full Day · 12h',
    price: '¥130,000',
    gradient: 'from-amber-900/80 via-yellow-800/60 to-orange-900/80',
    accent: '#D4A847',
    badge: 'Signature',
    emoji: '🏯',
    image: u('photo-1578469645742-46cae010e5d4'),
    imageHero: u('photo-1578469645742-46cae010e5d4') + '&w=1920',
    imageCard: u('photo-1578469645742-46cae010e5d4') + '&w=800&h=500',
    description: 'Ancient Kyoto temples at dawn, Nishiki Market at noon, bullet train to Osaka\'s electric Dotonbori at dusk. Two cities, two centuries, one legendary day.',
    longDescription: 'Dawn at Fushimi Inari before the crowds. The chaos and color of Nishiki Market. A hidden machiya lunch. Then the shinkansen to Osaka\'s kinetic energy — Dotonbori street food with Tony pointing out which stalls opened in 1902. The day ends at a rooftop bar with Osaka Castle illuminated below.',
    highlights: ['Fushimi Inari at absolute dawn', 'Nishiki Market food circuit', 'Hidden machiya lunch', 'Shinkansen city switch', 'Dotonbori street food tour', 'Osaka Castle rooftop view at night'],
    includes: ['Private guide 12h', 'All transit navigation', 'IC card top-up', 'Both city restaurant bookings', 'Cultural narrative both cities'],
    meetingPoint: 'Kyoto Station Central Exit',
    mapStops: [
      { name: 'Kyoto Station', lat: 34.9859, lng: 135.7588 },
      { name: 'Fushimi Inari Taisha', lat: 34.9671, lng: 135.7727 },
      { name: 'Nishiki Market', lat: 35.0051, lng: 135.7659 },
      { name: 'Dotonbori, Osaka', lat: 34.6687, lng: 135.5013 },
    ],
    languages: ['EN', 'ES', 'РУ', 'CS', 'AR'],
  },
  {
    id: 'mountain-hiking',
    route: 6,
    title: 'Mountain Hiking',
    subtitle: 'Kurama · Ancient Pilgrimage Trails',
    duration: 'Full Day · 9h',
    price: '¥108,000',
    gradient: 'from-emerald-900/80 via-teal-800/60 to-cyan-900/80',
    accent: '#10B981',
    badge: 'Adventure',
    emoji: '⛰️',
    image: u('photo-1448375240586-882707db888b'),
    imageHero: u('photo-1448375240586-882707db888b') + '&w=1920',
    imageCard: u('photo-1448375240586-882707db888b') + '&w=800&h=500',
    description: 'Walk the same mountain trails emperors walked seeking enlightenment. Cedar forests, moss-covered lanterns, mountain shrines, and a hidden waterfall on no map.',
    longDescription: 'The Kurama mountain trail north of Kyoto was walked by emperors seeking clarity — cedar forests, stone lanterns swallowed by moss, shrines smelling of centuries of incense. Tony walks the full trail, narrating the folklore of each landmark. Descend through Arashiyama\'s bamboo groves to a hidden waterfall meditation spot. End with a traditional tea ceremony in a garden overlooking the hills you just crossed.',
    highlights: ['Kurama pilgrimage trail — imperial route', 'Ancient cedar shrine forest', 'Hidden waterfall meditation spot', 'Arashiyama bamboo grove (off-hour)', 'Traditional tea ceremony in nature', 'Monkey park optional stop'],
    includes: ['Private guide all day', 'Trail navigation & safety', 'Forest shrine ritual explanation', 'Tea ceremony included', 'Packed snack recommendations'],
    meetingPoint: 'Kurama Station Exit',
    mapStops: [
      { name: 'Kurama Station', lat: 35.1197, lng: 135.7695 },
      { name: 'Kurama-dera Temple', lat: 35.1189, lng: 135.7676 },
      { name: 'Kibune Shrine', lat: 35.1318, lng: 135.7637 },
      { name: 'Arashiyama Bamboo Grove', lat: 35.0170, lng: 135.6720 },
    ],
    languages: ['EN', 'ES', 'РУ', 'CS', 'AR'],
  },
]

export const PRICING = [
  {
    id: 'essential',
    name: 'Essential',
    subtitle: 'Half Day',
    price: '¥75,000',
    priceUSD: '≈ $500',
    duration: '4–5 hours',
    features: ['Up to 4 guests', 'One city or area', 'Transit assistance', 'Flexible route', 'All 5 languages'],
    cta: 'Book Essential',
    hot: false,
  },
  {
    id: 'signature',
    name: 'Signature',
    subtitle: 'Full Day',
    price: '¥95,000–¥130,000',
    priceUSD: '≈ $635–$870',
    duration: '8–12 hours',
    features: ['Up to 6 guests', 'Multiple areas', 'Private transport option', 'Lunch recommendation', 'Cultural deep-dives', 'Evening extension option'],
    cta: 'Book Signature',
    hot: true,
  },
  {
    id: 'premium',
    name: 'Premium',
    subtitle: 'Kōyasan / Multi-Day',
    price: '¥165,000',
    priceUSD: '≈ $1,100',
    duration: 'Full day or multi-day',
    features: ['Unlimited guests', 'All Kansai region', 'Full itinerary design', 'Private transport', 'Restaurant reservations', 'Priority WhatsApp', '24h availability'],
    cta: 'Book Premium',
    hot: false,
  },
]

export const FAQS = [
  { q: 'Are tours truly private?', a: '100% private — your booking is exclusively yours. No other groups, no shared coaches. Just you and Tony with full attention on your experience.' },
  { q: 'How far in advance should I book?', a: 'Tony recommends 2–3 weeks ahead for weekends and peak seasons (March–May cherry blossom, October–November autumn). Weekday slots often available 1 week out.' },
  { q: 'What is the cancellation policy?', a: 'Full refund 72+ hours before the tour. 50% refund within 48 hours. No refund within 24 hours. Tony is flexible with reschedules — just reach out via WhatsApp.' },
  { q: 'Is transport included?', a: 'Tony assists with all transit navigation and IC card top-up. Private vehicle available for Premium package. Public transit is used for the authentic local experience.' },
  { q: 'Which languages do the guides speak?', a: 'Tony guides in English, Spanish and Arabic. Johnny guides in English and Czech. Larion guides in Russian, Japanese, English and Spanish — between the three of us, almost every guest feels right at home.' },
  { q: 'Can Tony help with restaurant reservations?', a: 'Absolutely. Tony has relationships with local restaurants including hidden spots that don\'t appear on any app. He pre-books in advance and pre-orders special dishes.' },
  { q: 'What areas does Tony cover?', a: 'Tony covers the full Kansai region: Osaka, Kyoto, Nara, Kobe, Himeji, Arashiyama, Kurama, Fushimi, Kōyasan, and more.' },
]

export const STATS = [
  { value: '7', label: 'Destinations', icon: '📍' },
  { value: '5', label: 'Languages', icon: '🌐' },
  { value: '100%', label: 'Private', icon: '🔒' },
]

const gu = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&q=85&w=600&h=600`

export const GUIDES = [
  {
    id: 'tony',
    name: 'Tony Hanma',
    role: 'Head Guide',
    rating: '5.0',
    photo: '/guides/guide-tony.jpg',
    accent: '#E53030',
    languages: ['🇬🇧', '🇪🇸', '🇸🇦'],
    langLabels: ['EN', 'ES', 'AR'],
    specialty: 'Food, Culture & History',
    bio: "The original Kansai insider. Tony built this company from his personal obsession with Osaka's hidden izakayas, Kyoto's secret temples, and the living stories behind every stone in the region.",
    highlights: ['Osaka Food Circuit', 'Hidden Kyoto', 'Osaka × Kyoto Grand Day'],
  },
  {
    id: 'johnny',
    name: 'Johnny Coletta',
    role: 'Senior Guide',
    rating: '5.0',
    photo: '/guides/guide-johnny.jpg',
    accent: '#FF6B35',
    languages: ['🇬🇧', '🇨🇿'],
    langLabels: ['EN', 'CS'],
    specialty: 'Architecture & Urban Secrets',
    bio: "Johnny's eye for architecture and urban design transforms every city walk into a visual masterclass. He knows every machiya townhouse in Kyoto and which alley hides the best ramen counter in Namba.",
    highlights: ['Hidden Kyoto', 'Kobe Refined', 'Nara Sacred Forest'],
  },
  {
    id: 'larion',
    name: 'Larion',
    role: 'Nature & Spiritual Guide',
    rating: '5.0',
    photo: '/guides/guide-larion.jpg',
    accent: '#8B5CF6',
    languages: ['🇷🇺', '🇯🇵', '🇬🇧', '🇪🇸'],
    langLabels: ['RU', 'JA', 'EN', 'ES'],
    specialty: 'Mountains, Temples & Pilgrimage',
    bio: 'Born to a Russian-Japanese family, Larion grew up between two worlds. Native in both languages, he accesses temples and ceremonies off-limits to most visitors — a perspective no guidebook can replicate.',
    highlights: ['Kōyasan Pilgrimage', 'Mountain Hiking', 'Nara Sacred Forest'],
  },
]

const h = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&q=85`

export const HIKING_ROUTES = [
  {
    id: 'mt-kongo',
    date: 'Apr 29, 2026',
    title: 'Mt. Kongo',
    subtitle: 'Highest Peak in Osaka Prefecture',
    altitude: '1,125 m',
    duration: '~2 h ascent',
    distance: null,
    location: 'Chihayaakasaka, Osaka / Nara border',
    access: 'Bus from Kawachinagano Station → Kongo-san mae',
    route: 'Chihayaguchi Trail · well marked',
    summit: 'Katsuragi Shrine · Observatory · Views of Osaka Bay and Nara',
    wildlife: 'Japanese macaques near the summit shrine',
    grade: 'Moderate',
    companions: 'with Johnny Koleta',
    note: 'Osaka and Nara divided by this ridge. One of the most respected peaks among local hikers in all Kansai.',
    badge: 'Osaka #1',
    accent: '#E53030',
    image: h('photo-1506905925346-21bda4d32df4'),
    imageCard: h('photo-1506905925346-21bda4d32df4') + '&w=800&h=500',
    mapStop: { lat: 34.4219, lng: 135.6656 },
    available: true,
  },
  {
    id: 'mt-wakakusa',
    date: 'Apr 30, 2026',
    title: 'Nara · Mt. Wakakusa',
    subtitle: 'Deer Park & Grass Summit',
    altitude: '342 m',
    duration: '3–4 h full loop',
    distance: null,
    location: 'Nara Koen + Wakakusayama · Nara',
    access: 'JR Yamatoji or Kintetsu Nara Line → Nara Station ~40 min',
    route: 'Deer Park → Todai-ji → Wakakusayama summit',
    summit: '342 m grass hill · three peaks · full panorama of Nara',
    wildlife: '~1,300 free-roaming sacred deer',
    grade: 'Easy–Moderate',
    companions: 'with Johnny Koleta',
    note: 'Wakakusa hilltop is almost always empty — the most underrated view in Nara.',
    badge: 'Hidden Gem',
    accent: '#22C55E',
    image: h('photo-1545569341-9eb8b30979d9'),
    imageCard: h('photo-1545569341-9eb8b30979d9') + '&w=800&h=500',
    mapStop: { lat: 34.6813, lng: 135.8449 },
    available: true,
  },
  {
    id: 'fukuchiyama-tunnels',
    date: 'May 4, 2026',
    title: 'Fukuchiyama Tunnels',
    subtitle: 'Abandoned Railway · Urbex Hike',
    altitude: null,
    duration: '4–5 h return',
    distance: '4.7 km one way',
    location: 'Old Fukuchiyama Line · Takarazuka, Hyogo',
    access: 'JR Takarazuka Line → Namaze · ¥800 r/t · Depart 07:30',
    route: 'Namaze Station → Takedao Station through 6 tunnels',
    summit: '6 tunnels · longest ~400 m of complete darkness · bats present',
    wildlife: 'Bats inside the tunnels',
    grade: 'Moderate · headlamp essential',
    companions: 'with Johnny Koleta',
    note: 'Without a real headlamp the second tunnel is impossible. 400 m of total darkness, wet floor, bats.',
    badge: 'Urbex',
    accent: '#64748B',
    image: h('photo-1510798831971-661eb04b3739'),
    imageCard: h('photo-1510798831971-661eb04b3739') + '&w=800&h=500',
    mapStop: { lat: 34.8058, lng: 135.3628 },
    available: true,
  },
  {
    id: 'mt-ikoma',
    date: 'May 5, 2026',
    title: 'Mt. Ikoma',
    subtitle: '6 Hours Lost · Spirit Realm Border',
    altitude: '642 m',
    duration: '6 h (lost route)',
    distance: null,
    location: 'Osaka / Nara border',
    access: 'Nukata Station · Kintetsu Osaka Line',
    route: 'South-face entry via Nukata Station · unmarked cedar forest paths',
    summit: 'Retro amusement park · Hozan-ji Shrine · cedar forest',
    wildlife: null,
    grade: 'Hard · unmarked trails',
    companions: 'with Johnny Koleta',
    note: 'Nukata Station is an almost unknown south-face entry point. Six hours without a map.',
    badge: 'Off-Trail',
    accent: '#8B5CF6',
    image: h('photo-1448375240586-882707db888b'),
    imageCard: h('photo-1448375240586-882707db888b') + '&w=800&h=500',
    mapStop: { lat: 34.6814, lng: 135.6972 },
    available: true,
  },
  {
    id: 'minoh-falls',
    date: 'May 7, 2026',
    title: 'Minoh Falls',
    subtitle: 'Maple Forest & Waterfall',
    altitude: null,
    duration: '2–3 h return',
    distance: '2.7 km',
    location: 'Minoo Park · Minoo City, Osaka',
    access: 'Hankyu Mino-o Line → Minoo Station · ~30 min · ¥400 r/t',
    route: 'Minoo Station → 33 m waterfall through maple forest',
    summit: '33 m waterfall · maple forest canopy',
    wildlife: 'Japanese macaques · do not feed',
    grade: 'Easy',
    companions: 'Solo',
    note: 'Thirty minutes from Osaka and it feels like a different world entirely.',
    badge: 'Family Friendly',
    accent: '#F97316',
    image: h('photo-1586348943529-beaae6c28db9'),
    imageCard: h('photo-1586348943529-beaae6c28db9') + '&w=800&h=500',
    mapStop: { lat: 34.8323, lng: 135.4706 },
    available: true,
  },
  {
    id: 'fushimi-inari',
    date: 'May 9, 2026',
    title: 'Fushimi Inari Mountain',
    subtitle: '10,000 Torii Gates · Full Summit',
    altitude: '233 m',
    duration: '2–3 h full ascent',
    distance: '4 km to summit',
    location: 'Fushimi Inari Taisha · Fushimi Ward, Kyoto',
    access: 'JR Nara Line → Inari Station · ¥300 · 2 min walk',
    route: '~10,000 orange torii gates · full 4 km climb to Mt. Inari',
    summit: 'Mt. Inari 233 m · upper trails nearly empty · overlooking all Kyoto',
    wildlife: null,
    grade: 'Easy–Moderate',
    companions: 'with Johnny Koleta',
    note: 'Upper trails are silent and empty — overlooking all of Kyoto. Most visitors never reach them.',
    badge: 'Most Popular',
    accent: '#E53030',
    image: h('photo-1524413840807-0c3cb6fa808d'),
    imageCard: h('photo-1524413840807-0c3cb6fa808d') + '&w=800&h=500',
    mapStop: { lat: 34.9671, lng: 135.7727 },
    available: true,
  },
  {
    id: 'ponpon-mountain',
    date: 'May 11, 2026',
    title: 'Ponpon Mountain',
    subtitle: 'Full Traverse · Triple City Views',
    altitude: '678 m',
    duration: '5–7 h point to point',
    distance: '12–15 km',
    location: 'Osaka / Kyoto border',
    access: 'Hankyu Takatsuki → summit → Hankyu Nagaokakyo',
    route: 'Takatsuki Station → summit → Nagaokakyo Station · full traverse',
    summit: 'Views of Kyoto, Osaka and Kobe simultaneously on clear days',
    wildlife: 'Japanese boar · walk quietly if encountered',
    grade: 'Medium–High · long route',
    companions: 'with Johnny Koleta',
    note: 'One of the most solitary mountains in Kansai. Very few hikers complete the full traverse.',
    badge: 'Full Traverse',
    accent: '#D4A847',
    image: h('photo-1464822759023-fed622ff2c3b'),
    imageCard: h('photo-1464822759023-fed622ff2c3b') + '&w=800&h=500',
    mapStop: { lat: 34.9006, lng: 135.6472 },
    available: true,
  },
  {
    id: 'zato-valley',
    date: 'May 14, 2026',
    title: 'Zato Valley',
    subtitle: '5 Hours Lost · Technical Off-Trail',
    altitude: null,
    duration: '5 h exploration',
    distance: null,
    location: 'Zato Valley · Rokko area, Hyogo',
    access: 'Rokko area · waterproof boots essential',
    route: 'Free exploration · no official trail · no signage',
    summit: 'Mountain stream · waterfalls · dense forest · granite boulders',
    wildlife: null,
    grade: 'Technical · experts only',
    companions: 'with Larion & Yuji',
    note: 'The hardest and most technical terrain of the entire diary. Zato Valley is not on any tourist map.',
    badge: 'Expert Only',
    accent: '#0EA5E9',
    image: h('photo-1433086966358-54859d0ed716'),
    imageCard: h('photo-1433086966358-54859d0ed716') + '&w=800&h=500',
    mapStop: { lat: 34.7800, lng: 135.2500 },
    available: false,
  },
  {
    id: 'hoshi-no-buranko',
    date: 'May 16, 2026',
    title: 'Hoshi no Buranko',
    subtitle: 'Sky Bridge + Ancient Meteor Shrine',
    altitude: null,
    duration: '5 h 20 min',
    distance: '14.1 km full loop',
    location: 'Katano City, Osaka Prefecture',
    access: 'Kintetsu Nara Line → Nozaki / Katano · ~40 min from Osaka · ¥500 r/t',
    route: 'Hanaten Station 09:17 → full loop descent · +1,287 m elevation gain',
    summit: 'Suspension bridge 280 m long · 50 m above forest canopy · Iwafune Jinja giant meteoric boulders',
    wildlife: null,
    grade: 'Medium · +1,287 m gain',
    companions: 'with Johnny Koleta',
    note: 'The bridge cuts through the tree canopy at 50 meters — nothing below. Iwafune\'s boulders are unlike anything else in Kansai.',
    badge: 'Iconic',
    accent: '#10B981',
    image: h('photo-1441974231531-c6227db76b6e'),
    imageCard: h('photo-1441974231531-c6227db76b6e') + '&w=800&h=500',
    mapStop: { lat: 34.8044, lng: 135.6742 },
    available: true,
  },
  {
    id: 'sky-house-daito',
    date: 'May 21, 2026',
    title: 'Sky House · Daito',
    subtitle: 'Hillside Urbex · Abandoned Hotel',
    altitude: null,
    duration: '3–4 h exploration',
    distance: null,
    location: 'Nakagaito, Daito, Osaka',
    access: 'JR Osaka Higashisen → Shigino or JR Katamachi Line → Shijonawate',
    route: 'Mountain hillside trails around abandoned Sky House hotel',
    summit: 'Abandoned hotel swallowed by forest · retro sign still standing',
    wildlife: null,
    grade: 'Moderate · urban exploration',
    companions: 'Solo',
    note: 'The Sky House sign still stands on its rusted pole. The building has been completely swallowed by the hillside trees.',
    badge: 'Urbex',
    accent: '#64748B',
    image: h('photo-1518181835702-6eef8b4b2113'),
    imageCard: h('photo-1518181835702-6eef8b4b2113') + '&w=800&h=500',
    mapStop: { lat: 34.7167, lng: 135.6333 },
    available: false,
  },
  {
    id: 'mt-hiei',
    date: 'May 23, 2026',
    title: 'Mt. Hiei',
    subtitle: '1,200 Years of Buddhism',
    altitude: '848 m',
    duration: '~3 h ascent',
    distance: null,
    location: 'Kyoto / Shiga border',
    access: 'Eizan Railway → Yase-Hieizanguchi → Cable car · ¥1,700 r/t · ~1.5 h from Osaka',
    route: 'Mudoji-dani Trail · dense cedar forest',
    summit: 'Enryakuji Temple complex · founded 788 AD · ¥1,000 entry',
    wildlife: 'Deer and tanuki · silent forest above city noise',
    grade: 'Moderate',
    companions: 'Solo',
    note: 'Standing at Enryakuji in the mist, the city disappears completely. One of Japan\'s most sacred mountains.',
    badge: 'Sacred',
    accent: '#8B5CF6',
    image: h('photo-1528360983277-13d401cdc186'),
    imageCard: h('photo-1528360983277-13d401cdc186') + '&w=800&h=500',
    mapStop: { lat: 35.0725, lng: 135.8381 },
    available: true,
  },
  {
    id: 'mt-maya',
    date: 'May 25, 2026',
    title: 'Mt. Maya',
    subtitle: 'Million Dollar Night View · Kobe',
    altitude: '702 m',
    duration: '~2.5 h ascent',
    distance: null,
    location: 'Nada Ward, Kobe, Hyogo',
    access: 'Hankyu → Sannomiya → Bus → Nunobiki → Ropeway · ¥1,840 r/t · ~1 h from Osaka',
    route: 'Tenjojo Trail · forest and rocky ridgeline',
    summit: 'Maiko Park · "Million Dollar Night View of Japan" over Kobe Bay',
    wildlife: null,
    grade: 'Moderate',
    companions: 'Solo',
    note: 'The view from Maiko Park at dusk over Kobe\'s harbor is one of the most dramatic in all Japan. The night view alone is worth the climb.',
    badge: 'Best Views',
    accent: '#0EA5E9',
    image: h('photo-1540959733332-eab4deabeeaf'),
    imageCard: h('photo-1540959733332-eab4deabeeaf') + '&w=800&h=500',
    mapStop: { lat: 34.7342, lng: 135.2353 },
    available: true,
  },
]

export const TESTIMONIALS: { name: string; country: string; tour: string; rating: number; text: string }[] = []

export const LANGUAGES = [
  { flag: '🇬🇧', name: 'English', code: 'EN' },
  { flag: '🇪🇸', name: 'Spanish', code: 'ES' },
  { flag: '🇷🇺', name: 'Russian', code: 'РУ' },
  { flag: '🇨🇿', name: 'Czech', code: 'CS' },
  { flag: '🇸🇦', name: 'Arabic', code: 'AR' },
]
